### ISSUE TITLE
Plugin does not show workflow error messages

### ISSUE THREAD

**Issue by jk1** [jk1/youtrack-idea-plugin#101]
What steps will reproduce the problem?

Define a workflow rule on issue state with an error message
Try to change issue state through YouTrack integration plugin
What is the expected result?
We expect to receive a notification in intellij with the custom error message

What happens instead?
Intellij shows a generic error with the stacktrace and not the custom error messate

**Comment by basteez** [comment]
In addition, if it helps, [here's the stacktrace returned by the plugin](https://github.com/jk1/youtrack-idea-plugin/files/3381032/stacktrace.txt)

**Comment by jk1** [comment]
The fix is to be included in 0.9.6
