### ISSUE TITLE
empowering the use of the plugin API

### ISSUE THREAD

**Issue by Elmo397** [jk1/youtrack-idea-plugin#102]
It is necessary to give an opportunity to get all issues from YouTrack by query (query like "#Kotlin for: me"). Also necessary to have the opportunity to change states of issues and to get users with all possible information about them.

**Comment by jk1** [comment]
> to get all issues from YouTrack by query (query like "#Kotlin for: me")

This is certainly possible and seems to fit the plugin API concept

> have the opportunity to change states of issues

One should be careful with that. It is possible to configure YouTrack project to have no field named *State*, even with no state concept at all. What can we do from a plugin side is to provide an api to execute commands. It's up to you to handle a; possible configuration quirks, as well as command execution errors. e.g. from workflows.

> to get users with all possible information about them

Now this is where things got complicated. 
- User information is a subject of GDPR and cannot be shared w/o proper consideration and adequate protection measures
- On requires a lot of permissions to fetch this data. To be a server admin, in fact, no less.
- Plugin does not operate users, so there's nothing to share via the api
- Most importantly, it's Hub where user data resides, not YouTrack

**Comment by Elmo397** [comment]
> What we can do from a plugin side is to provide an API to execute commands.
Yes, provide us an API to execute commands. Thank you! When you can do it?

**Comment by Elmo397** [comment]
When can you update the varsion in https://plugins.jetbrains.com/plugin/8215-youtrack-integration/versions so that I can depend on my plugin?

**Comment by jk1** [comment]
@Elmo397 I would advice to try the following build first and to make sure the API has everything you need and works in accordance with your expectations. Should it prove to be the case,then  we get it published.

https://github.com/jk1/youtrack-idea-plugin/blob/master/api/src/main/java/com/github/jk1/ytplugin/YouTrackPluginApi.java

[ytplugin-0.9.8.zip](https://github.com/jk1/youtrack-idea-plugin/files/3426750/ytplugin-0.9.8.zip)

**Comment by jk1** [comment]
@Elmo397 please let me know if current implementation covers your needs so I can release it. If not, please describe issues you're having with it.
