### ISSUE TITLE
issues with 'Open multiple projects in one window' in WebStorm

### ISSUE THREAD

**Issue by regevbr** [jk1/youtrack-idea-plugin#103]
In WebStorm 2019.2 (released just a few days ago) they added a really cool and usefull feature (https://www.jetbrains.com/webstorm/whatsnew/) called "Open multiple projects in one window".

This feature allows to have multiple projects opened at the same window, and as such the git context is changed based on what project the file you are currently working on belongs to.

When I start working on an issue, and open a new branch for it using this awesome plugin, it creates the feature branch to ALL open projects - which we can discuss if it good or bad. But what really bothers me is that when you finish with the issue and change the task back to the default task, it only restores the current working branch on the current project context, leaving all other projects stuck on the feature branch... Which of-course leads me to changing them all back to the master branch manually (and for 13 projects it takes a long time)

I'm not sure if this is an issue with WebStorm tasks management, or with the plugin itself. @jk1 do you have any idea what went wrong here?

**Comment by regevbr** [comment]
I think the best solution here is to only checkout the branch in the current git context.
As to task managment - the solution should be based on how webstorm handled the tasks context and sadly I don't know anything about it. We do need to consider working on the same issue on multiple projects simultaneously while allowing to remove a project from the task when you are done with it, without closing the task.

**Comment by regevbr** [comment]
Might be a WebStorm only issue. I opened a bug there - https://youtrack.jetbrains.com/issue/JT-53570

**Comment by jk1** [comment]
@regevbr right you are, this part is managed by a bundled Task Management plugin
