### ISSUE TITLE
Cannot delete "Issue navigation" setting

### ISSUE THREAD

**Issue by jbeckers** [jk1/youtrack-idea-plugin#105]
I have this setup:
![image](https://user-images.githubusercontent.com/379626/64243394-90a58c80-cf07-11e9-8ee6-866c2938abb3.png)

Somehow JIRA issue links in the version control history tool window are detected as youtrack issue links.

I'd like to be able to remove the YouTrack Issue navigation setting, but the plugin keeps re-adding it.

**Comment by jk1** [comment]
Hi there.
It may be a  bit too late to address, but still. Latest YouTrack plugin versions use a more precise regexp now, matching only real project IDs and not everything that looks like an issue.
