### ISSUE TITLE
username auth will be deprecated soon

### ISSUE THREAD

**Issue by regevbr** [jk1/youtrack-idea-plugin#109]
According to https://blog.jetbrains.com/youtrack/2019/08/features-to-be-discontinued-in-upcoming-youtrack-releases/ the username/password auth method will be deprecated in 2020.1 (will be probably released around March 2020)

I believe we should already migrate to the token auth method, to be prepared and also to be able to disable username/password logins to youtrack itslef when only oauth is really needed (currently I have the username/password method auth on, just for this plugin)

i.e.
The blog alos talks about deprecating the old api. Not sure if it is applicable here, but should be taken under consideration as well.

@jk1 what say you?

**Comment by regevbr** [comment]
it seems that this actually relies on the youtrack server configuration to change and that is not in our hands, which contradicts their desire to make such a change...
I opened an issue to get that going - https://youtrack.jetbrains.com/issue/JT-54447, please vote it up

**Comment by jk1** [comment]
@regevbr token auth is actually supported by the plugin. Setting either a permanent token or an app password as a password in IDE should do the trick. Since it's not at all obvious, I probably should at least add a readme section to cover that.

> which contradicts their desire to make such a change...

As far as I know the server form is something that's being worked on at the moment.

**Comment by regevbr** [comment]
Thanks, that is very strange that it works as the code doesnt seem to handle it at all and it should be sent in a diffrent way than Basic auth. Can you please explain how it works as well?

**Comment by regevbr** [comment]
I see that youtrack actually takes care of the matter for us, as it disregards the username when using perm token within a basic auth

**Comment by jk1** [comment]
Right you are, YouTrack accepts tokens as passwords in `Authorization Basic` header to let existing clients connect while they're not yet migrated to the `Auhtorization Bearer`.
