### ISSUE TITLE
Password/token lost on Android Studio at each start

### ISSUE THREAD

**Issue by NitroG42** [jk1/youtrack-idea-plugin#119]
The plugin is really great and I'm kinda used to the new workflow, unfortunatelly I have a small issue with Android Studio which reset the password each time the IDE is closed (the field is blank).
I tried with a password and a token but to the same result unfortunatelly.
I'm using Windows 10 if it's revelant.
I used two different Android Studio (4.0 and 4.1) both has issue and the last one is based on Intellij 2020.1.

**Comment by jk1** [comment]
The plugin doesn't store passwords and tokens by itself, delegating to the native IDE secure store feature instead. It might be that you have selected "Do not save, forget password after restart" in **Appearance & Behavior | System Settings | Passwords** in settings. 

Could you please check if this is indeed the case?

**Comment by NitroG42** [comment]
Ah yes I thought about that but forgot to check how the passwords were saved in the IDE.
It should works now, thanks !
