### ISSUE TITLE
java.net.BindException: Address already in use

### ISSUE THREAD

**Issue by tgoetz** [jk1/youtrack-idea-plugin#12]
I get the following exception when opening the "Open Task" dialog, also the issue list from youtrack is not updated any more.
This seems to happens since the update to version 0.2 of the youtrack plugin.

```
com.github.jk1.ytplugin.navigator.components.SourceNavigatorComponent@16de606b: Address already in use
java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.$$YJP$$socketBind(Native Method)
	at java.net.PlainSocketImpl.socketBind(PlainSocketImpl.java)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:382)
	at java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.bind(ServerSocket.java:329)
	at fi.iki.elonen.NanoHTTPD$ServerRunnable.run(NanoHTTPD.java:1687)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tgoetz** [comment]
On which port does the nanoHttpd run? Maybe I have something else running on that port?

**Comment by jk1** [comment]
It tries to listen on ports from 63330 till 63339. It's still a bug though, as occupied port is not expected to affect issue list.

**Comment by jk1** [comment]
A graceful fallback has been implemeted

**Comment by tgoetz** [comment]
Any chance of creating a new release any time soon? I'm looking forward to continue using the plugin ...

**Comment by jk1** [comment]
@tgoetz, would you mind trying a fixed build first? I failed to get the very same exception as you did even with required ports occupied. What I've implemented here is a general fallback, so I'd like to know if it really fixes the problem for you before releasing it.

Here's the build with a fix: https://www.dropbox.com/s/vuef7qvbkrszllo/ytplugin-0.2.1.zip?dl=0

Thanks in advance.

**Comment by tgoetz** [comment]
I tried the build, now I get the following warning when starting IDEA:
"YouTrack plugin error: Can't listen on ports 63330 to 63339. 'Open in IDE' feature will be disabled". It looks like the list of tasks does *not* get refreshed also, at least I can't find newly created task in the list when opening the "Open Task " dialog.

**Comment by jk1** [comment]
Do these newly created tasks match a search query in YouTrack repository settings?

**Comment by tgoetz** [comment]
Hm? I simply started typing the ticket description ...

**Comment by jk1** [comment]
Here's the search query I am talking about: https://www.dropbox.com/s/9s9ltabu1im4kre/tasks.png?dl=0
Task management in Idea is designed to filter tasks for "Open Task" dialog by this query.

**Comment by tgoetz** [comment]
Ok, got it! The task was unassigned and the filter contained "assigned to me". Thanks for the hint!

**Comment by jk1** [comment]
That explains much) I'm glad we finally got this sorted out.

**Comment by tgoetz** [comment]
Yeah, me too. Thanks again for your support!
