### ISSUE TITLE
Password not remembered after PHPStorm restart

### ISSUE THREAD

**Issue by evotodi** [jk1/youtrack-idea-plugin#127]
The youtrack password is randomly forgotten after restarting PHPStorm. 
Tried uninstalling the plugin but that made no difference because after restart and reinstall the setting were already filled in without the password.

**Comment by jk1** [comment]
Hi @evotodi 
Please make sure that the IDE is configured to store passwords:

![image](https://user-images.githubusercontent.com/715844/89559876-e9b82780-d81e-11ea-9291-5b201a9546de.png)

**Comment by evotodi** [comment]
My bad! That was the issue.
Thank you.
