### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by BazMaster** [jk1/youtrack-idea-plugin#128]
I don't know why I can't connect to my account. 
Server URLs may not be supported: https://*****.myjetbrains.com ?

![image](https://user-images.githubusercontent.com/2923303/89696788-1d2faa80-d922-11ea-96f8-ea12f03cad0a.png)

**Comment by jk1** [comment]
Hi @BazMaster,

For YouTrack InCloud a correct URL would be https://*****.myjetbrains.com/youtrack. Just as seen in a browser address bar.

**Comment by BazMaster** [comment]
Perfectly! 
Everything works! 
Thanks!
