### ISSUE TITLE
New setup dialog doesn't persist passwords, or so it seems

### ISSUE THREAD

**Issue by jk1** [jk1/youtrack-idea-plugin#129]
Steps to reproduce:

1. Configure a new connection to YouTrack server. Make sure it's green and issues can be loaded.
2. Restart the IDE
3. Try to refresh the issue list 

Expected result:  Issues are updated from the server
Actual result: Authentication errors

**Comment by lesslyrics** [comment]
Fixed, the issue was with input token, see[ b6a39bc](https://github.com/jk1/youtrack-idea-plugin/commit/b6a39bcee5bb9e253aeca8e978a43c64cca72e97)

**Comment by jk1** [comment]
@lesslyrics that's great to hear. Let's close the issue then.
