### ISSUE TITLE
unable to create youtrack issue from intellij using youtrack plugin

### ISSUE THREAD

**Issue by SalahALivres** [jk1/youtrack-idea-plugin#133]
After selecting a piece of code, I am trying to create a Youtrack issue from IntelliJ using the context menu but nothing happens : no message, no window opening ... 
This is the same situation when using the "Create Issue" button in the youtrack window : no message, no window opening... 

I use the cloud version of youtrack. I can view issues opened in the Cloud so connection is OK.

IntelliJ Ultimate version : 2020.2
YouTrack Plugin verion 1.0.0OS : windows 7, 64 bits

**Comment by SalahALivres** [comment]
Helle, I just wanted to say, that I installed the update plugin 1.0.1, and the bug seems to be fixed. Thank you.

**Comment by jk1** [comment]
@SalahALivres thank you for the update.
It's good to know that the problem is resolved.
