### ISSUE TITLE
PyCharm: fails to connect even if 'Test Connection' from settings reports success.

### ISSUE THREAD

**Issue by serge-gaia** [jk1/youtrack-idea-plugin#150]
Context:
* Pycharm Pro 2020.2
* YT plugin version: 1.0.5
* Ubuntu 20.4

The plugin reports a 'Can't connect to YouTrack server. Are you offline?'. I test my connection in the server settings both from global Settings menu and from plugin Setup Dialog (which looks all squashy by the way) and it reports success.

I've been using this plugin for a long time and it's been working so far (is it a 1.0.5 problem?).

How reliable is the 'Test Connection' from the settings menu?

**Comment by jk1** [comment]
Hi @serge-gaia,

Thank you for getting in touch.
May I ask you what YouTrack version you're using?

**Comment by serge-gaia** [comment]
It says: Build 2020.4.4701

**Comment by serge-gaia** [comment]
Looking at YouTrack release calendar, I'd say that the timing is about right between the release of 2020.4 and the plugin not working.

**Comment by jk1** [comment]
I see, thank you. 
I believe you've faced a known YouTrack issue https://youtrack.jetbrains.com/issue/JT-60911

**Comment by serge-gaia** [comment]
I see. Thank you.
