### ISSUE TITLE
Tracking mode automatic freezes entire UI

### ISSUE THREAD

**Issue by jowilkes** [jk1/youtrack-idea-plugin#155]
Selecting Time tracking mode "Automatic" in YouTrack Integration 1.1.2 freezes entire IntelliJ UI; if setting was saved, this happens every time it is restarted. Process had to be killed; removing this behaviour was only possible by changing the settings in the .idea/workspace.xml. ( timeTracker.isAutoTrackingEnable to false, and/or timeTracker.isAutoTrackingTemporaryDisabled to true)

Reproduced this reliably over a dozen times in the past 3 hours, so I'm quite sure of this bug.
The issue seems to be the requester for "select valid active task" which (intentionally?) blocks the rest of the UI, but also itself and the task selection, so it cannot be completed. -> deadlock. Maybe this requester was modal by accident.

Versions:
- YouTrack Integration 1.1.2, 
- IntellJ 2020.3.1, 
- YouTrack  Build 2020.6.1767 Thu, Dec 17, 2020, 12:21:05 PM UTC

**Comment by jk1** [comment]
I'm afraid I failed to reproduce the problem.
Would it be possible for you to define a clear sequence of steps leading to it?

Attaching a freeze dump from the IDE log folder would also help.
