### ISSUE TITLE
URL to Attachments are broken due shortened YouTrack-Domain

### ISSUE THREAD

**Issue by dennis-heinrich** [jk1/youtrack-idea-plugin#161]
The Attachment on the Ticket points to a shortend string of the complete URL. The Attachment in the YouTrack Instance can be opened and isn't corrupted. It might be a problem with the IDEA-Plugin.

**Example for a broken Attachment Link:**
![image](https://user-images.githubusercontent.com/4189795/108266030-df7dcb00-7169-11eb-98a5-7da7a2d65154.png)

**Correct URL Behaviour for the Link to the Ticket:** 
![image](https://user-images.githubusercontent.com/4189795/108266194-18b63b00-716a-11eb-9f41-ef5caeab11cf.png)

**Comment by lesslyrics** [comment]
relates to [#157](https://github.com/jk1/youtrack-idea-plugin/issues/157)

**Comment by lesslyrics** [comment]
Fixed, expected to be released in 1.1.5

**Comment by lesslyrics** [comment]
It is now released in 1.1.5
