### ISSUE TITLE
Plugin not available for Rider EAP

### ISSUE THREAD

**Issue by thecodemonk** [jk1/youtrack-idea-plugin#165]
I'm on the 2021 EAP 9 and I've been really missing the YouTrack plugin since I started using the EAP. Since we are closer to release can we get the plugin made available again, or is this something that has to wait for the release of Rider?

**Comment by jk1** [comment]
Thank you for reminding me about it.
I'll check what needs to be fixed in the plugin to accommodate platform updates. Hopefully it won't take long.

**Comment by sergyu91ma** [comment]
we need this update, as 2021 has been released

**Comment by jk1** [comment]
Thank you for your patience.
YouTrack plugin 1.2.0 is out now, it should be compatible with 2021.1 IDEA platform.
