### ISSUE TITLE
Buttons and links on panel won't work if integration wasn't done using a permanent token.

### ISSUE THREAD

**Issue by AplouroVV** [jk1/youtrack-idea-plugin#167]
Plugin version: 
1.2.0
PHPStorm Version: 
PhpStorm 2021.1
Build #PS-211.6693.120, built on April 7, 2021

On the youtrack panel no buttons or links work (and no tasks are shown) if the integration wasn't done using a permanent token.
Since the buttons nor links will work you will have to use the menus Settings-Tasks-Server to insert a permanent token. After that the buttons in the panel will work and the tasks will appear.

**Comment by jk1** [comment]
Hi @AplouroVV,

Thank you for reporting it. Am I getting it right that you had login\password auth configured before?

**Comment by AplouroVV** [comment]
Yes I did. Sorry for not being explicit.
It was a project that I hadn't opened in a while and still was using login\password.

**Comment by jk1** [comment]
Got it, thanks. It should definitely be possible to open the plugin settings dialog and reconfigure everything.
Will check it out.

**Comment by jk1** [comment]
Fixed in 1.2.1
