### ISSUE TITLE
New tool window show non-english characters incorrectly.

### ISSUE THREAD

**Issue by saroff** [jk1/youtrack-idea-plugin#23]
In our project we have Cyrrilic names for issues, they are displayed correctly in drop-down menu on top, but in new tool window there is encoding problem:

![2016-08-08_1008](https://cloud.githubusercontent.com/assets/6500849/17471907/46cf0f22-5d50-11e6-90c8-d5e65658e118.png)
![2016-08-08_1007](https://cloud.githubusercontent.com/assets/6500849/17471911/4a8f0e8c-5d50-11e6-9efd-2c68f6bc3feb.png)

**Comment by jk1** [comment]
Thank you for reporting it. I suppose you faced the problem on Windows machine, as the problem requires a non-Unicode default charset to be reproduced.

Adding -Dfile.encoding=UTF8 to idea64.vmoptions file may help until the fix is delivered.
