### ISSUE TITLE
YouTrack Plugin text encoding bug

### ISSUE THREAD

**Issue by wuhao000** [jk1/youtrack-idea-plugin#28]
Chinese character cannot be displayed correctly
![image](https://cloud.githubusercontent.com/assets/6957904/18409453/03d8c318-777a-11e6-9240-4bee36fec371.png)

**Comment by jk1** [comment]
Thank you for reporting it.
Which plugin version you're using?

**Comment by wuhao000** [comment]
The newest version，I just installed it several days ago.

发自我的 iPhone

**Comment by wuhao000** [comment]
The plugin version I used is 0.4

**Comment by wuhao000** [comment]
I hope this bug can be fixed as soon as possible because it is so important for my team

**Comment by jk1** [comment]
Thanks to your assistance I managed to reproduce the problem. The fix is coming soon.

**Comment by jk1** [comment]
Fixed in 0.4.1

**Comment by wuhao000** [comment]
Wow, it is a real suprise.
The infomation displayed correctly now.
