### ISSUE TITLE
Open YT Command dialog from UI button

### ISSUE THREAD

**Issue by cautionbug** [jk1/youtrack-idea-plugin#29]
Just discovered this plugin and already love it. Steady progress is encouraging.

The recent addition of executing commands on YT issues using the YT Command dialog is great! Can you also add a button to the panel UI to open the dialog? i had to come here to find out it's available from a keyboard shortcut. i found no other access to it from the panel or menus.

Thanks!

**Comment by jk1** [comment]
Thank you for suggestion, it sounds like a reasonable and useful proposal to me.
Although the command dialog launcher is also available under "Tools" menu, I would agree that it is not an immediately evident feature.
