### ISSUE TITLE
Show issues across projects.

### ISSUE THREAD

**Issue by danhalson** [jk1/youtrack-idea-plugin#30]
I'm unable to show issues across multiple projects. My search query is:

project: {Project 1}, {Project 2} AND (Developer: me OR Assignee: me) AND State: {In Progress}, ...

But I only get results when I remove one of the projects.

Thanks, Dan.

**Comment by jk1** [comment]
Does this query return anything in YouTrack web UI?

**Comment by jk1** [comment]
Nevermind, I was able to reproduce it.

**Comment by danhalson** [comment]
Saw your comment too late, but great, thanks for this.

**Comment by jk1** [comment]
You're always welcome)
