### ISSUE TITLE
Authentication via 3rd Party

### ISSUE THREAD

**Issue by vonox7** [jk1/youtrack-idea-plugin#45]
Username/Password is only one way to authenticate a user in YouTrack. Because of lack of 2-factor-authentication in YouTrack, all our team members authenticate them via Google or Github. Please add a way to integrate 3rd party login into this plugin too.

**Comment by jk1** [comment]
This one may be tricky to implement without a bit of support from YouTrack itself. 
What would you say about the following flow:

1. A user defines a personal authentication token in his/her YouTrack profile, just like it can be done on GitHub at the moment
2. This token is used in IDE for authentication instead of the login/password pair

Does it sound like a solution to your problem?

**Comment by vonox7** [comment]
That would be totally a solution!

**Comment by jk1** [comment]
That's great to know. I was told that the token feature will make it into the next YouTrack version, so it would be possible for me to support it in the plugin.

**Comment by regevbr** [comment]
This is already implemented in youtrack, would be great to have that feature!

**Comment by regevbr** [comment]
Really wanted to do a pull request but the problem's root lies deep in the intellij code as they use old apache http componenets (3.1) which doesn't come with an easy solution for using the barear auth model required here...

**Comment by jk1** [comment]
That is why the ticket is hanging here for a while. Thanks for looking into it anyway.
The good news is that YouTrack will start accepting oauth tokens via http basic auth header soon. And this is exactly what we need to get the current feature request implemented.

**Comment by YoungjaeKim** [comment]
I’m trying to adopt YT to biggest Asian corp, but cannot do because of this.

**Comment by jk1** [comment]
Got everything ready for that on plugin side. All we need now is to wait for YouTrack 2018.1 to arrive.
With YouTrack 2018.1 it will be possible to use permanent tokens as passwords. This approach is also considered to be generally more secure.

**Comment by YoungjaeKim** [comment]
Sorry to poke you @jk1 
Is there any issue till now? Nothing changed till 2018.3 😢

**Comment by jk1** [comment]
@YoungjaeKim the plugin supports permanent tokens as passwords atm. YouTrack 2018.3 also understands them, so it should work. I've tested it myself just now and it works indeed.
