### ISSUE TITLE
Proper filtering

### ISSUE THREAD

**Issue by danmichaelson** [jk1/youtrack-idea-plugin#46]
The type to search feature is kind of handy but also a pretty confusing UI. More importantly it doesn't support proper YouTrack searches such as on an issue state. An actual filter feature that uses the REST API would be really handy here. e.g. search for "#unresolved".

Admittedly you can accomplish it by changing the server configuration but this feels a little weird to do all the time.

**Comment by jk1** [comment]
Fair enough. Current implementation is based on what task management plugin had to offer out of the box and that was a search string defined in server settings. 

While this feature is not implemented one can configure several servers with different searches and have them displayed in tabs. That approach works for me and can probably ease the pain from a missing search control for now.
