### ISSUE TITLE
Comments Tab in Issue Preview Covers Descriptions

### ISSUE THREAD

**Issue by slavaatsig** [jk1/youtrack-idea-plugin#63]
In issue preview rendering “Comments” tab slightly covering the bottom of the issue description.

**As seen on the YouTrack:**
![As seen on the Youtrack](https://cloud.githubusercontent.com/assets/17236178/26201554/3f7a66d4-3bdc-11e7-90e3-0110308dc858.png)

**As seen in the plugin:**
![As rendered in the plugin](https://cloud.githubusercontent.com/assets/17236178/26201576/5cbbf23a-3bdc-11e7-9bf5-607c857e9f20.png)

_You can notice that the last link “Brands Groups” is totally covered by the title “Comments (1)”._

System Info:
IntelliJ IDEA 2017.1.3
Build #IU-171.4424.56, built on May 12, 2017
JRE: 1.8.0_112-release-736-b21 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-75-generic

YouTrack Integration Plugin Version: 0.7

**Comment by jk1** [comment]
Fixed in 0.7.1
