### ISSUE TITLE
Query doesn't seem to work?

### ISSUE THREAD

**Issue by jamesallsup** [jk1/youtrack-idea-plugin#65]
This module is great! I was almost ready to ditch YouTrack as I wanted it to display in PHPStorm but the interface was poor until I found this!

Anyway I'm running Storm 2017.1.4 from Toolbox, installed the plugin and setup great - shows my issues just fine. The query doesn't work for me though, I have tried setting in both server config and the top bar but neither take affect, it is always ordered by the issue ID (asc).

Is this a known issue or am I missing something?

Thanks!

**Comment by jamesallsup** [comment]
Sorry I should have e been more clear with that!

No none of the queries work at all - even tried basic filtering by project etc

.

**Comment by jk1** [comment]
That's interesting. 
Would you mind turning debug logging on, reproduce the issue once again and post the log file here? If insure how to do that feel free to check the readme page.

Thanks in advance.

**Comment by jk1** [comment]
Closing. Please let me know if any further assistance is required here.
