### ISSUE TITLE
Unable to install in Gogland 171.4694.35

### ISSUE THREAD

**Issue by papricasix** [jk1/youtrack-idea-plugin#66]
Hi,

when I try to install this plugin via the IDE settings of Gogland, I get the following messages:

![2017-07-01](https://user-images.githubusercontent.com/3974712/27762097-d854e9a0-5e6a-11e7-9cf1-36becda60c84.png)
![2017-07-01 1](https://user-images.githubusercontent.com/3974712/27762096-d83f7b56-5e6a-11e7-8258-ff4760545861.png)

Michael

**Comment by jk1** [comment]
@papricasix thank you for reporting this. 

YouTrack integration plugin depends on an another plugin - bundled Task Management Plugin. It seems like the latter cannot be installed on a recent Gogland build. I'll ask JetBrains, let's see what they have to say about it.

**Comment by papricasix** [comment]
Cool, thanks!

**Comment by jk1** [comment]
So it turned out to be an IDE plugin lookup bug: https://youtrack.jetbrains.com/issue/IDEA-175375

Meanwhile there's a workaround available:
1. Navigate to File | Settings | Plugins | Browse Repositories
2. Search for "Task Management" plugin and install it
3. Install YouTrack Integration plugin

**Comment by papricasix** [comment]
Very nice, thank you for your effort and your plugin!
