### ISSUE TITLE
Add API to open tool window pointing to specific issue 

### ISSUE THREAD

**Issue by VladRassokhin** [jk1/youtrack-idea-plugin#68]
I'd like to integrate this plugin with '[Tasks Naviagtion](https://plugins.jetbrains.com/plugin/7241-tasks-navigation)' one.
So 'go to definition' or 'ctrl+click' would open tool window instead of browser.

**Comment by jk1** [comment]
Implemented in 0.7.2. Please refer to readme.md on where to find it.
