### ISSUE TITLE
Can't comment for all

### ISSUE THREAD

**Issue by Olegt0rr** [jk1/youtrack-idea-plugin#69]
In command window I try to leave comment, but in field "Visible for groups" I can't choose Visible for all, only groups. But on free plan account of YouTrack there's no way to leave comments for groups.
I got error, that I can't set group visibility for comments, cause license restrictions applied for me.

Please make ability to post comments for all.

**Comment by jk1** [comment]
I'd say it's a bug. All Users group definitely should be in the list.

**Comment by jk1** [comment]
Fixed in 0.7.2
