### ISSUE TITLE
Update Labels for Tooltips

### ISSUE THREAD

**Issue by scotta451** [jk1/youtrack-idea-plugin#70]
A few suggestions to improve the labels on the UI:

-  Change **Refresh issues** to simply read **Refresh**. The *YouTrack Issues* title in the tool window tells you what you're refreshing. If you prefer it to remain as is, use title capitalization: **Refresh Issues**.
- Change **Set as active task** to **Open Task**, as that's the title of the dialog that is opened with this control.
- Change **Toggle issue list presentation** to **Toggle Presentation**.
- Add a tooltip (**Search**) to the search icon.

**Comment by jk1** [comment]
Thanks for suggestion, fixed.
