### ISSUE TITLE
Add Open Command Dialog to toolbar

### ISSUE THREAD

**Issue by scotta451** [jk1/youtrack-idea-plugin#71]
It's a great feature, but it's not discoverable.

- Add an icon to the toolbar
- For the tooltip, use **Open Command Dialog (shortcut)**

That should make it easier for users to discover the feature and memorize the keyboard shortcut.

**Comment by jk1** [comment]
I guess it's on the toolbar already:

![image](https://user-images.githubusercontent.com/715844/30689516-d994ec94-9ec9-11e7-82fc-23bdc1923207.png)

Or do you mean some other toolbar?

**Comment by scotta451** [comment]
Bloody hell - I totally overlooked it up there. I expected to see it in the tool window for the plugin:

![image](https://user-images.githubusercontent.com/16539758/30689729-1d77cb0a-9ec2-11e7-87d8-6f43596bc707.png)

Personally, I think it's better to have it in the tool window. If you'd rather leave it where it is, we can address it in docs and demos.

In any case, please update the tooltip.

**Comment by jk1** [comment]
> In any case, please update the tooltip.
Sure, no objections here.

Going back to command window: the actual reason for it be up there is the fact that it's applied to an active IDE task, so the button resides right near the task selector. It's not the same thing as the selected issue in command window.

Probably it's a good idea to make command window work with currently selected issue instead.

**Comment by scotta451** [comment]
>Probably it's a good idea to make command window work with currently selected issue instead.

And, to be consistent with YouTrack, support multi-select in the tool window.
