### ISSUE TITLE
Allow preview pane to be placed below ticket list

### ISSUE THREAD

**Issue by bittner** [jk1/youtrack-idea-plugin#74]
I prefer to have the YouTrack pane on the right side of the IDE. That allows me to use the screen real estate of the wide screens better.

Current Behavior
---------------------
Currently, this has the disadvantage that I only see the list, not the preview pane. The preview pane is collapsed by default, and if I open it I need to make the side panel unusually wide to make reading both the ticket list and the text in the preview pane comfortable.

Expected Behavior
----------------------
It would be good if users could change the layout of the panel, and place the preview pane below the ticket list. Similar as with popular email clients that usually allow you to either rearrange panes or choose between layouts.

**Comment by jk1** [comment]
That's a fair expectation, I guess it can be implemented. 
Meanwhile one can use 'Pin issue' action as a poor man's substitute.

**Comment by bittner** [comment]
Ah, "Pin issue" is nice! When you know it.  :smiley: 

But unpinning is difficult. Or impossible?  </off_topic>
