### ISSUE TITLE
How to spent time in a task?

### ISSUE THREAD

**Issue by alvaromarco** [jk1/youtrack-idea-plugin#81]
It's possible set spent time in a task from plugin? Maybe it's a good idea for the future

**Comment by jk1** [comment]
Yes it is: https://www.jetbrains.com/help/youtrack/standalone/Time-Tracking-IDE-Integration.html

**Comment by alvaromarco** [comment]
@jk1 I use Android Studio and not show Time Tracking in Settings > Tools > Tasks. I configure Youtrack plugin correctly and i can select tasks for example. What's wrong?

**Comment by jk1** [comment]
So it's about Android Studio?
Time tracking feature is implemented as separate time tracking plugin by JetBrains.
Apparently they ship it only with IDEs based on IJ Ultimate Edition, while Android Studio is based on IJ Community Edition.

https://www.jetbrains.com/help/idea/managing-tasks-and-contexts.html#time_tracking

**Comment by alvaromarco** [comment]
Yes it's about Android Studio. Is not possible for now...

**Comment by jk1** [comment]
There's also another option how to do that. Invoke command dialog and report time via command:

![image](https://user-images.githubusercontent.com/715844/37587958-d5062e38-2b71-11e8-821d-878cdc0180cb.png)

**Comment by alvaromarco** [comment]
Ok thanks!
