### ISSUE TITLE
Id and Description are not added to Changelist title in IntelliJ 2018.3

### ISSUE THREAD

**Issue by Wallaby1999** [jk1/youtrack-idea-plugin#89]
When pressing "Open Task" the dialog "Open Task" dialog is shown, but the name for the changelist is empty. Before 2018.3 id and summary were pre-filled as the name for the changelist.
Also tried to change some settings like the commit message, but it had no effect.

Can I somehow support tracking down this bug?

**Comment by jk1** [comment]
I believe this to be an Intellij issue: https://youtrack.jetbrains.com/issue/IDEA-202675
They seem to have some troubles finding the exact steps to reproduce the problem though.

**Comment by Wallaby1999** [comment]
Thanks a lot for your very quick reply. Will follow up there.
