### ISSUE TITLE
Branch naming configuration

### ISSUE THREAD

**Issue by Darkilen** [jk1/youtrack-idea-plugin#92]
Hello,

Each time I go to a new issue, I create a new branch for her. I use gitflow branch naming, so I need to add a prefix every time (`feature/`, `hotfix/`, `release/`, `support/`)
It would be great to have a place to configure somes prefix/suffix that can be use when we create/switch to a branch when we're using this plugin.

**Comment by jk1** [comment]
Hi,

This is something implemented outside of the plugin. Branch naming can be configured to a certain extent via Settings -> Tools->Tasks window. See also https://youtrack.jetbrains.com/issue/IDEA-155327 if current configuration options don't fit your workflow.

**Comment by Darkilen** [comment]
[IDEA-155327](https://youtrack.jetbrains.com/issue/IDEA-155327) is exactly what I'm looking for. I'll watch it and hope they'll add it :wink:
