### ISSUE TITLE
command autocomplete not working with youtrack 2019.1

### ISSUE THREAD

**Issue by regevbr** [jk1/youtrack-idea-plugin#95]
After upgrading to youtrack 2019.1 the command auto completion stopped working...
Not sure how to see the logs to send it here, please advise

**Comment by jk1** [comment]
Thank you for reporting it.
It seems to be a YouTrack bug though. Reported it as https://youtrack.jetbrains.com/issue/JT-52363.

**Comment by regevbr** [comment]
Thanks it is working now with latest version of your plugin and latest youtrack
