### ISSUE TITLE
state list is not popluated

### ISSUE THREAD

**Issue by regevbr** [jk1/youtrack-idea-plugin#96]
Just upgraded to youtrack version 2019.1.51277 and the state list is empty in the `open task` dialog under the `update issue state` field
No visible errors are thrown to the UI

**Comment by regevbr** [comment]
@jk1 can you please have a look at that issue?

**Comment by jk1** [comment]
@regevbr this is a YouTrack REST API bug.
I've been told the fix is already there and all we can do is to wait for it to be released.

**Comment by regevbr** [comment]
Can you send the issue link please?

**Comment by jk1** [comment]
Unfortunately, I have none.

**Comment by regevbr** [comment]
I confirm it is indeed fixed by youtrack in the 2019.1.51759 docker hub tag
